Added documentation on Message class
yourWaifu/sleepy-discord pull request #193
Opened 2020-11-30 04:09 UTC by FloweyTheFlower420

Added documentation for public member variables in the Message class, so people don't have to scroll through to find the author of a message. There may be some issues with indention, but ill fix it later

2020-11-30 04:19 UTC, yourWaifu requested changes

2020-11-30 04:19 UTC, yourWaifu commented on source/documentation.html.md
> +std::sstring editedTimestamp;
extra s

2020-11-30 04:19 UTC, yourWaifu commented on source/documentation.html.md
> +List of everyone mention in this message.
remove everyone

2020-11-30 04:19 UTC, yourWaifu commented on source/documentation.html.md
> +The origin of the message.
not sure why this is here.

2020-11-30 14:52 UTC, FloweyTheFlower420 commented
Hey sorry, im kinda a idiot, and i will be creating another pull request.

2020-11-30 14:53 UTC, FloweyTheFlower420 commented
wait i think i figured it out lol

2020-12-01 05:27 UTC, yourWaifu approved these changes

2020-12-01 05:28 UTC, merged

2020-12-01 05:29 UTC, yourWaifu commented
Don't worry if changes don't show up yet, I still have to deploy it.